name: Deploy page
on:
  schedule:
    - cron:  '0 22 * * *'    # 国际标准时间22点（北京时间早上6点发） 
  push:
    branches:    
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true


jobs:
  push:
      runs-on: ${{ matrix.operating-system }}
      strategy:
        matrix:
          # in this example, there is a newer version already installed, 3.7.7, so the older version will be downloaded
          operating-system: ['ubuntu-20.04']
      steps:
      - uses: actions/checkout@v3 # Checking out the repo
      - name: Setup Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Install dependencies
        run: yarn install

      - name: Build README.md
        run: node main.js
      
      - name: Commit and push if changed   # 更新html
        run: |
          git diff
          git config --global user.email "bin@aha.run"
          git config --global user.name "Aha-run"
          git add .
          git commit -m "Github Action auto Updated"
          git push

      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1